## UK House Prices Analysis

Source
https://www.gov.uk/government/statistical-data-sets/uk-house-price-index-data-downloads-december-

Information on dataset
https://www.gov.uk/government/publications/about-the-uk-house-price-index/about-the-uk-house-price-index#data-tables

In [61]:
import numpy as np
import os
import pandas as pd

In [63]:
filepath = "../data/UK-HPI-full-file-2025-12.csv"

#### Create a dataframe from csv

In [27]:
data = pd.read_csv(filepath)

#### Examine data

In [38]:
print(f"Data shape:{data.shape}")
data.head()

Data shape:(149085, 54)

,Date,RegionName,AreaCode,AveragePrice,Index,IndexSA,1m%Change,12m%Change,AveragePriceSA,SalesVolume,...,NewPrice,NewIndex,New1m%Change,New12m%Change,NewSalesVolume,OldPrice,OldIndex,Old1m%Change,Old12m%Change,OldSalesVolume
0,01/01/2004,Aberdeenshire,S12000034,84638,41.1,NaN,NaN,NaN,NaN,388.0,...,112843.0,40.7,NaN,NaN,103.0,81273.0,41.0,NaN,NaN,285.0
1,01/02/2004,Aberdeenshire,S12000034,84623,41.1,NaN,0.0,NaN,NaN,326.0,...,113061.0,40.8,0.2,NaN,107.0,81194.0,40.9,-0.1,NaN,219.0
2,01/03/2004,Aberdeenshire,S12000034,86536,42.1,NaN,2.3,NaN,NaN,453.0,...,115218.0,41.6,1.9,NaN,140.0,83137.0,41.9,2.4,NaN,313.0
3,01/04/2004,Aberdeenshire,S12000034,87373,42.5,NaN,1.0,NaN,NaN,571.0,...,115247.0,41.6,0.0,NaN,180.0,84241.0,42.5,1.3,NaN,391.0
4,01/05/2004,Aberdeenshire,S12000034,89493,43.5,NaN,2.4,NaN,NaN,502.0,...,117377.0,42.4,1.8,NaN,167.0,86466.0,43.6,2.6,NaN,335.0

In [43]:
data.describe()

,AveragePrice,Index,IndexSA,1m%Change,12m%Change,AveragePriceSA,SalesVolume,DetachedPrice,DetachedIndex,Detached1m%Change,...,NewPrice,NewIndex,New1m%Change,New12m%Change,NewSalesVolume,OldPrice,OldIndex,Old1m%Change,Old12m%Change,OldSalesVolume
count,1.490850e+05,149085.000000,5244.000000,148632.000000,144225.000000,5244.000000,144618.000000,1.422840e+05,142284.000000,141889.000000,...,1.416640e+05,141664.000000,141268.000000,136936.000000,138483.000000,1.418680e+05,141868.000000,141472.000000,137140.000000,141858.000000
mean,1.831012e+05,59.835763,62.132113,0.526866,6.100826,168752.656941,1252.600105,3.420380e+05,59.933395,0.461848,...,2.196692e+05,61.681981,0.497958,6.245756,135.956161,1.847985e+05,60.045649,0.472946,6.054274,1138.200045
std,1.311841e+05,26.619737,25.039764,1.934405,8.622357,94882.354669,7707.191260,3.432452e+05,25.206280,1.697813,...,1.342548e+05,26.401143,1.751680,7.974581,843.840990,1.310111e+05,25.507217,1.730925,8.408653,6965.933714
min,2.553000e+03,0.800000,13.900000,-30.300000,-35.800000,39008.000000,2.000000,4.011700e+04,9.400000,-19.600000,...,2.244300e+04,8.000000,-29.800000,-28.900000,1.000000,2.271600e+04,9.000000,-30.600000,-30.300000,2.000000
25%,1.005410e+05,38.200000,46.600000,-0.500000,1.100000,116135.000000,140.000000,1.785228e+05,41.200000,-0.500000,...,1.279912e+05,42.400000,-0.500000,1.700000,10.000000,1.021160e+05,40.900000,-0.500000,1.000000,126.000000
50%,1.547560e+05,61.000000,62.600000,0.500000,5.100000,153018.500000,215.000000,2.603840e+05,60.000000,0.400000,...,1.982200e+05,61.600000,0.500000,5.400000,21.000000,1.549365e+05,60.800000,0.500000,5.100000,193.000000
75%,2.301380e+05,80.300000,80.400000,1.400000,10.100000,209241.750000,376.000000,3.961765e+05,79.800000,1.400000,...,2.780390e+05,82.800000,1.500000,10.100000,46.000000,2.312262e+05,79.600000,1.400000,10.200000,343.000000
max,1.656986e+06,153.100000,110.000000,35.300000,98.400000,574627.000000,183609.000000,5.820174e+06,147.000000,34.800000,...,1.414204e+06,149.600000,34.900000,96.200000,21097.000000,1.665089e+06,152.700000,35.600000,98.600000,166098.000000

In [111]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 149085 entries, 0 to 149084
Data columns (total 54 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Date                    149085 non-null  str
 1   RegionName              149085 non-null  str
 2   AreaCode                149085 non-null  str
 3   AveragePrice            149085 non-null  int64
 4   Index                   149085 non-null  float64
 5   IndexSA                 5244 non-null    float64
 6   1m%Change               148632 non-null  float64
 7   12m%Change              144225 non-null  float64
 8   AveragePriceSA          5244 non-null    float64
 9   SalesVolume             144618 non-null  float64
 10  DetachedPrice           142284 non-null  float64
 11  DetachedIndex           142284 non-null  float64
 12  Detached1m%Change       141889 non-null  float64
 13  Detached12m%Change      137568 non-null  float64
 14  SemiDetachedPrice       142284 non-null  float64
 15  SemiDetachedIndex       142284 non-null  float64
 16  SemiDetached1m%Change   141889 non-null  float64
 17  SemiDetached12m%Change  137568 non-null  float64
 18  TerracedPrice           142395 non-null  float64
 19  TerracedIndex           142395 non-null  float64
 20  Terraced1m%Change       141999 non-null  float64
 21  Terraced12m%Change      137667 non-null  float64
 22  FlatPrice               142656 non-null  float64
 23  FlatIndex               142656 non-null  float64
 24  Flat1m%Change           142260 non-null  float64
 25  Flat12m%Change          137928 non-null  float64
 26  CashPrice               65856 non-null   float64
 27  CashIndex               65856 non-null   float64
 28  Cash1m%Change           65464 non-null   float64
 29  Cash12m%Change          61152 non-null   float64
 30  CashSalesVolume         65068 non-null   float64
 31  MortgagePrice           65856 non-null   float64
 32  MortgageIndex           65856 non-null   float64
 33  Mortgage1m%Change       65464 non-null   float64
 34  Mortgage12m%Change      61152 non-null   float64
 35  MortgageSalesVolume     65070 non-null   float64
 36  FTBPrice                66252 non-null   float64
 37  FTBIndex                66252 non-null   float64
 38  FTB1m%Change            65860 non-null   float64
 39  FTB12m%Change           61548 non-null   float64
 40  FOOPrice                65856 non-null   float64
 41  FOOIndex                65856 non-null   float64
 42  FOO1m%Change            65464 non-null   float64
 43  FOO12m%Change           61152 non-null   float64
 44  NewPrice                141664 non-null  float64
 45  NewIndex                141664 non-null  float64
 46  New1m%Change            141268 non-null  float64
 47  New12m%Change           136936 non-null  float64
 48  NewSalesVolume          138483 non-null  float64
 49  OldPrice                141868 non-null  float64
 50  OldIndex                141868 non-null  float64
 51  Old1m%Change            141472 non-null  float64
 52  Old12m%Change           137140 non-null  float64
 53  OldSalesVolume          141858 non-null  float64
dtypes: float64(50), int64(1), str(3)
memory usage: 61.4 MB

#### Review missing variables

In [57]:
data.isna().sum(axis=0)

Date                           0
RegionName                     0
AreaCode                       0
AveragePrice                   0
Index                          0
IndexSA                   143841
1m%Change                    453
12m%Change                  4860
AveragePriceSA            143841
SalesVolume                 4467
DetachedPrice               6801
DetachedIndex               6801
Detached1m%Change           7196
Detached12m%Change         11517
SemiDetachedPrice           6801
SemiDetachedIndex           6801
SemiDetached1m%Change       7196
SemiDetached12m%Change     11517
TerracedPrice               6690
TerracedIndex               6690
Terraced1m%Change           7086
Terraced12m%Change         11418
FlatPrice                   6429
FlatIndex                   6429
Flat1m%Change               6825
Flat12m%Change             11157
CashPrice                  83229
CashIndex                  83229
Cash1m%Change              83621
Cash12m%Change             87933
CashSalesVolume            84017
MortgagePrice              83229
MortgageIndex              83229
Mortgage1m%Change          83621
Mortgage12m%Change         87933
MortgageSalesVolume        84015
FTBPrice                   82833
FTBIndex                   82833
FTB1m%Change               83225
FTB12m%Change              87537
FOOPrice                   83229
FOOIndex                   83229
FOO1m%Change               83621
FOO12m%Change              87933
NewPrice                    7421
NewIndex                    7421
New1m%Change                7817
New12m%Change              12149
NewSalesVolume             10602
OldPrice                    7217
OldIndex                    7217
Old1m%Change                7613
Old12m%Change              11945
OldSalesVolume              7227
dtype: int64

### Investigating area codes

In [86]:
unique_area_codes = data['AreaCode'].unique()
print(set([i[0] for i in unique_area_codes]))

{'N', 'K', 'S', 'W', 'E'}

In [92]:
print(set([i[0:3] for i in unique_area_codes]))

{'E11', 'K04', 'E12', 'N92', 'E13', 'E07', 'E10', 'E08', 'S12', 'E06', 'E09', 'S92', 'W06', 'N09', 'E92', 'K02', 'W92', 'K03'}

In [116]:
total_area_codes = len(unique_area_codes)
idx = 0
while idx <= total_area_codes:
    print(unique_area_codes[idx:idx+10])
    idx = idx+10

['E06000001', 'E06000002', 'E06000003', 'E06000004', 'E06000005', 'E06000006', 'E06000007', 'E06000008', 'E06000009', 'E06000010']
['E06000011', 'E06000012', 'E06000013', 'E06000014', 'E06000015', 'E06000016', 'E06000017', 'E06000018', 'E06000019', 'E06000020']
['E06000021', 'E06000022', 'E06000023', 'E06000024', 'E06000025', 'E06000026', 'E06000027', 'E06000030', 'E06000031', 'E06000032']
['E06000033', 'E06000034', 'E06000035', 'E06000036', 'E06000037', 'E06000038', 'E06000039', 'E06000040', 'E06000041', 'E06000042']
['E06000043', 'E06000044', 'E06000045', 'E06000046', 'E06000047', 'E06000049', 'E06000050', 'E06000051', 'E06000052', 'E06000054']
['E06000055', 'E06000056', 'E06000057', 'E06000058', 'E06000059', 'E06000060', 'E06000061', 'E06000062', 'E06000063', 'E06000064']
['E06000065', 'E06000066', 'E07000008', 'E07000009', 'E07000010', 'E07000011', 'E07000012', 'E07000032', 'E07000033', 'E07000034']
['E07000035', 'E07000036', 'E07000037', 'E07000038', 'E07000039', 'E07000040', 'E07000041', 'E07000042', 'E07000043', 'E07000044']
['E07000045', 'E07000046', 'E07000047', 'E07000061', 'E07000062', 'E07000063', 'E07000064', 'E07000065', 'E07000066', 'E07000067']
['E07000068', 'E07000069', 'E07000070', 'E07000071', 'E07000072', 'E07000073', 'E07000074', 'E07000075', 'E07000076', 'E07000077']
['E07000078', 'E07000079', 'E07000080', 'E07000081', 'E07000082', 'E07000083', 'E07000084', 'E07000085', 'E07000086', 'E07000087']
['E07000088', 'E07000089', 'E07000090', 'E07000091', 'E07000092', 'E07000093', 'E07000094', 'E07000095', 'E07000096', 'E07000098']
['E07000099', 'E07000102', 'E07000103', 'E07000105', 'E07000106', 'E07000107', 'E07000108', 'E07000109', 'E07000110', 'E07000111']
['E07000112', 'E07000113', 'E07000114', 'E07000115', 'E07000116', 'E07000117', 'E07000118', 'E07000119', 'E07000120', 'E07000121']
['E07000122', 'E07000123', 'E07000124', 'E07000125', 'E07000126', 'E07000127', 'E07000128', 'E07000129', 'E07000130', 'E07000131']
['E07000132', 'E07000133', 'E07000134', 'E07000135', 'E07000136', 'E07000137', 'E07000138', 'E07000139', 'E07000140', 'E07000141']
['E07000142', 'E07000143', 'E07000144', 'E07000145', 'E07000146', 'E07000147', 'E07000148', 'E07000149', 'E07000170', 'E07000171']
['E07000172', 'E07000173', 'E07000174', 'E07000175', 'E07000176', 'E07000177', 'E07000178', 'E07000179', 'E07000180', 'E07000181']
['E07000192', 'E07000193', 'E07000194', 'E07000195', 'E07000196', 'E07000197', 'E07000198', 'E07000199', 'E07000200', 'E07000202']
['E07000203', 'E07000207', 'E07000208', 'E07000209', 'E07000210', 'E07000211', 'E07000212', 'E07000213', 'E07000214', 'E07000215']
['E07000216', 'E07000217', 'E07000218', 'E07000219', 'E07000220', 'E07000221', 'E07000222', 'E07000223', 'E07000224', 'E07000225']
['E07000226', 'E07000227', 'E07000228', 'E07000229', 'E07000234', 'E07000235', 'E07000236', 'E07000237', 'E07000238', 'E07000239']
['E07000240', 'E07000241', 'E07000242', 'E07000243', 'E07000244', 'E07000245', 'E08000001', 'E08000002', 'E08000003', 'E08000004']
['E08000005', 'E08000006', 'E08000007', 'E08000008', 'E08000009', 'E08000010', 'E08000011', 'E08000012', 'E08000013', 'E08000014']
['E08000015', 'E08000017', 'E08000018', 'E08000021', 'E08000022', 'E08000023', 'E08000024', 'E08000025', 'E08000026', 'E08000027']
['E08000028', 'E08000029', 'E08000030', 'E08000031', 'E08000032', 'E08000033', 'E08000034', 'E08000035', 'E08000036', 'E08000037']
['E08000038', 'E08000039', 'E09000001', 'E09000002', 'E09000003', 'E09000004', 'E09000005', 'E09000006', 'E09000007', 'E09000008']
['E09000009', 'E09000010', 'E09000011', 'E09000012', 'E09000013', 'E09000014', 'E09000015', 'E09000016', 'E09000017', 'E09000018']
['E09000019', 'E09000020', 'E09000021', 'E09000022', 'E09000023', 'E09000024', 'E09000025', 'E09000026', 'E09000027', 'E09000028']
['E09000029', 'E09000030', 'E09000031', 'E09000032', 'E09000033', 'E10000003', 'E10000007', 'E10000008', 'E10000011', 'E10000012']
['E10000013', 'E10000014', 'E10000015', 'E10000016', 'E10000017', 'E10000018', 'E10000019', 'E10000020', 'E10000024', 'E10000025']
['E10000028', 'E10000029', 'E10000030', 'E10000031', 'E10000032', 'E10000034', 'E11000001', 'E11000002', 'E11000003', 'E11000005']
['E11000006', 'E11000007', 'E12000001', 'E12000002', 'E12000003', 'E12000004', 'E12000005', 'E12000006', 'E12000007', 'E12000008']
['E12000009', 'E13000001', 'E13000002', 'E92000001', 'K02000001', 'K03000001', 'K04000001', 'N09000001', 'N09000002', 'N09000003']
['N09000004', 'N09000005', 'N09000006', 'N09000007', 'N09000008', 'N09000009', 'N09000010', 'N09000011', 'N92000002', 'S12000005']
['S12000006', 'S12000008', 'S12000010', 'S12000011', 'S12000013', 'S12000014', 'S12000017', 'S12000018', 'S12000019', 'S12000020']
['S12000021', 'S12000023', 'S12000026', 'S12000027', 'S12000028', 'S12000029', 'S12000030', 'S12000033', 'S12000034', 'S12000035']
['S12000036', 'S12000038', 'S12000039', 'S12000040', 'S12000041', 'S12000042', 'S12000045', 'S12000047', 'S12000048', 'S12000049']
['S12000050', 'S92000003', 'W06000001', 'W06000002', 'W06000003', 'W06000004', 'W06000005', 'W06000006', 'W06000008', 'W06000009']
['W06000010', 'W06000011', 'W06000012', 'W06000013', 'W06000014', 'W06000015', 'W06000016', 'W06000018', 'W06000019', 'W06000020']
['W06000021', 'W06000022', 'W06000023', 'W06000024', 'W92000004']

Area codes appear to be in format N-01-000-001, where the first letter is a country code, next two digits a regional code then last 3 a county / unitary / district authority or london borough.

There are country codes; E,K,N,S,W. These could be England, ?, Northern Ireland, Scotland and Wales.
The secondary codes for E are : 06 to 13 and 92.
The secondary codes for K are 02-04.
The secondary codes for N are 09,92.
The secondary codes for S are 12.
The secondary codes for W are 06,92.

In [137]:
### create a region column
data['Region'] = data['AreaCode'].str[0]

         Date     RegionName   AreaCode  AveragePrice  Index  IndexSA  \
0  01/01/2004  Aberdeenshire  S12000034         84638   41.1      NaN
1  01/02/2004  Aberdeenshire  S12000034         84623   41.1      NaN
2  01/03/2004  Aberdeenshire  S12000034         86536   42.1      NaN
3  01/04/2004  Aberdeenshire  S12000034         87373   42.5      NaN
4  01/05/2004  Aberdeenshire  S12000034         89493   43.5      NaN

   1m%Change  12m%Change  AveragePriceSA  SalesVolume  ...  NewIndex  \
0        NaN         NaN             NaN        388.0  ...      40.7
1        0.0         NaN             NaN        326.0  ...      40.8
2        2.3         NaN             NaN        453.0  ...      41.6
3        1.0         NaN             NaN        571.0  ...      41.6
4        2.4         NaN             NaN        502.0  ...      42.4

   New1m%Change  New12m%Change  NewSalesVolume  OldPrice  OldIndex  \
0           NaN            NaN           103.0   81273.0      41.0
1           0.2            NaN           107.0   81194.0      40.9
2           1.9            NaN           140.0   83137.0      41.9
3           0.0            NaN           180.0   84241.0      42.5
4           1.8            NaN           167.0   86466.0      43.6

   Old1m%Change  Old12m%Change  OldSalesVolume  Region
0           NaN            NaN           285.0       S
1          -0.1            NaN           219.0       S
2           2.4            NaN           313.0       S
3           1.3            NaN           391.0       S
4           2.6            NaN           335.0       S

[5 rows x 55 columns]

### Use the government uk counties and unitary boundaries map
https://www.data.gov.uk/dataset/85228aec-fe0e-49bf-9455-df000d61e731/counties-and-unitary-authorities-may-2023-boundaries-uk-bgc

In [129]:
import geopandas as gpd
geodata = "../data/uk-counties.geojson"
map_df = gpd.read_file(geodata)
print(map_df.columns)

Index(['FID', 'CTYUA23CD', 'CTYUA23NM', 'CTYUA23NMW', 'BNG_E', 'BNG_N', 'LONG',
       'LAT', 'GlobalID', 'geometry'],
      dtype='str')